# Generated by Django 4.2.5 on 2024-01-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shut', models.BooleanField(default=False)),
                ('budget', models.FloatField(default=1000)),
                ('squadSize', models.IntegerField(default=11)),
                ('sameSquadMax', models.IntegerField(default=4)),
                ('reactivity', models.FloatField(default=1.0)),
            ],
        ),
    ]
