# Generated by Django 4.2.5 on 2025-09-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_transferwindow'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this player currently active and selectable?'),
        ),
        migrations.AlterField(
            model_name='fantasy',
            name='chemistry',
            field=models.FloatField(default=0.0),
        ),
    ]
